### PR TITLE
Scaffold the Google Protobuf bits

### PR DESCRIPTION
**Pull request by bladyjoker**
DONE
- Added lambda-buffers-proto with a specified CompilerInput message,
- Added lambda-buffers-compiler Cabal project with a Hello World that uses the codegenerated CompilerInput.
- Provided the Nix structure that glues things together and does code quality automation and CI instructions

### CODE REVIEW

**Comment by bladyjoker** [comment]
@gnumonik can you please check the direnv workflow as for some reason it breaks in `lambda-buffers-compiler` directory for me. I wonder if the issue is reproducible.
Essentially got to `lambda-buffers-compiler` directory and do `direnv allow` or `direnv reload` when necessary.

**Comment by bladyjoker** [comment]
> @gnumonik can you please check the direnv workflow as for some reason it breaks in `lambda-buffers-compiler` directory for me. I wonder if the issue is reproducible.
> Essentially got to `lambda-buffers-compiler` directory and do `direnv allow` or `direnv reload` when necessary.

I had an older version of nix-direnv -.-

Either `nix profile upgrade nixpkgs#nix-direnv` or `nix profile list | grep nix-direnv` to find the package and remove it with `nix profile remove #number` and install the latest version `nix profile install nixpkgs#nix-direnv`

**Review by gnumonik — APPROVED** [review]
For some reason this PR breaks my direnv (which afaict is up to date). `nix develop` works though. Going to approve but not merge for right now since everything looks OK and everything appears to work w/ `nix develop`

**Comment by bladyjoker** [comment]
Thanks @gnumonik , I'll merge this and we can proceed with fixes in the following PRs.

**Pull request merged**
